import type { NextPage } from "next";
import Head from "next/head";

import Component from "../components";

const Home: NextPage = () => {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex items-center justify-center min-h-screen'>
        <Component />
      </main>
    </div>
  );
};

export default Home;
